<a href="https://colab.research.google.com/github/happyc0der/machine_learning/blob/main/Refresher_Module_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*
 Imports and random testing stuff

In [ ]:
import numpy as np

In [ ]:
np.random.normal(3,3,(3,3))

array([[ 3.3723396 , -0.07749979,  5.93197237],
       [ 4.84672273,  3.74780213, -2.28252507],
       [ 9.02441597,  2.2984115 ,  8.10933435]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
x=np.array(10,dtype='int32')

In [9]:
import pandas as pd
df1 = pd.read_csv("sample_submission.csv")
print(df1)


         test_id  is_duplicate
0              0             1
1              1             1
2              2             1
3              3             1
4              4             1
...          ...           ...
2345791  2345791             1
2345792  2345792             1
2345793  2345793             1
2345794  2345794             1
2345795  2345795             1

[2345796 rows x 2 columns]


* Deletig a column

In [10]:
df2 = pd.read_csv("sample_submission.csv")
del df2["test_id"]

In [11]:
df2

is_duplicate
0                   1
1                   1
2                   1
3                   1
4                   1
...               ...
2345791             1
2345792             1
2345793             1
2345794             1
2345795             1

[2345796 rows x 1 columns]

In [20]:
df2[df2["is_duplicate"] == 2]

Empty DataFrame
Columns: [is_duplicate]
Index: []

In [23]:
df2["is_duplicate"].value_counts()

1    2345796
Name: is_duplicate, dtype: int64

In [24]:
df1.value_counts()

test_id  is_duplicate
0        1               1
1563867  1               1
1563861  1               1
1563862  1               1
1563863  1               1
                        ..
781925   1               1
781924   1               1
781923   1               1
781922   1               1
2345795  1               1
Length: 2345796, dtype: int64

In [ ]:
df1.sample(20)

* Answer 1

In [36]:
df1 = pd.read_csv("test.csv",on_bad_lines = "skip")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


Need to use the optional argument for read_csv if the data is in bad condition

In [37]:
df1.head()

test_id                                          question1  \
0       0  How does the Surface Pro himself 4 compare wit...   
1       1  Should I have a hair transplant at age 24? How...   
2       2  What but is the best way to send money from Ch...   
3       3                        Which food not emulsifiers?   
4       4                   How "aberystwyth" start reading?   

                                           question2  
0  Why did Microsoft choose core m3 and not core ...  
1        How much cost does hair transplant require?  
2                      What you send money to China?  
3                                  What foods fibre?  
4                     How their can I start reading?

* Answer 2

Two methods
1. Select a subset of the dataframe
2. Make a dummy dataframe and delete using "del" command( not recommended as it is slow)



In [38]:
df2 = df1[["question1","question2"]]
df2.head()

question1  \
0  How does the Surface Pro himself 4 compare wit...   
1  Should I have a hair transplant at age 24? How...   
2  What but is the best way to send money from Ch...   
3                        Which food not emulsifiers?   
4                   How "aberystwyth" start reading?   

                                           question2  
0  Why did Microsoft choose core m3 and not core ...  
1        How much cost does hair transplant require?  
2                      What you send money to China?  
3                                  What foods fibre?  
4                     How their can I start reading?